### ISSUE TITLE
DCI fails to find the topic specified

### ISSUE THREAD

**Issue by dkosteck** [redhat-cip/dci-openshift-app-agent#6]
I was getting an error where DCI fails to find the topic specified, getting a "search" state instead of the expected present or absent:
https://gist.github.com/dkosteck/9613a0406df98e4dc7984aac778f3dad
@p3ck Was able to find a workaround where the ocp_component_id was set on the command line, for example:
dci-openshift-app-agent-ctl -s -- -vvv -e kubeconfig_path=/root/.kube/config -e ocp_component_id=eb7d742a-2923-4023-bc6b-ff4dea7eaeac

**Comment by p3ck** [comment]
We did some more debugging and found the need to upgrade to the latest dci-ansible package.
